### PR TITLE
[GUI] aaaaaaaaaaaaaa

### PR DESCRIPTION
**Pull request by hitman-resources**
just merge it

### CODE REVIEW

**Comment by hitman-resources** [comment]
looks good to @Notexe

**Comment by Notexe** [comment]
> looks good to @Notexe

The failed build totally agrees

**Comment by hitman-resources** [comment]
looks good to @Notexe

**Comment by hitman-resources** [comment]
new gui overhaul, look up rule #34

**Comment by hitman-resources** [comment]
amendment: it is not an overhaul but a minor change

i am sorry for the distress this may have caused

@Notexe will personally compensate you all with $5 per person

**Comment by hitman-resources** [comment]
please look good to @Notexe i beg of you github actions

**Comment by hitman-resources** [comment]
looks good to @Notexe

**Comment by hitman-resources** [comment]
c# i will end you

**Comment by hitman-resources** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Pull request merged**
