### PR TITLE
Tony's PR

### PR DESCRIPTION
**Pull request by AnthonyFuller**
Doing more things to this PR, just seeing if it will run a build. Will update title and description when complete.

### CODE REVIEW

**Comment by RDIL** [comment]
do we need spectre mitigations enabled for lz4?

**Review by RDIL — CHANGES_REQUESTED** [review]
Build time needs to improve before this can be merged.

**Comment by AnthonyFuller** [comment]
I can't do much about that, you either get better support (ResourceLib can now be anywhere where Windows usually looks for it, unlike before), or you get better build times.

**Comment by Notexe** [comment]
Is this PR ready to be merged or is there still things you are working on in it?

**Review by RDIL — APPROVED** [review]
lgtm

**Comment by RDIL** [comment]
Feel free to merge if everything works.

**Pull request merged**
